# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

# PREVENT SECRETS FROM BEING EXPOSED TO GITHUB AND PUBLIC
# https://stackoverflow.com/questions/31689674/how-do-you-keep-secrets-yml-secret-in-rails
development:
  secret_key_base: 0ef332c414c85f3c617243709825c65dee013a3486b370316eeaaaf77c0a8a671eecef30f252dede3da0ab7c02ce1078e498ef6899d929baa5e94bb506a1eb56

test:
  secret_key_base: 5b7210ca45bdc293c92a4b4176b6a2eb9f841cf1a09a0b41f42c83509944b66d61fb0458b11f97c2695afa4720070f4a71b45ac6f623378283a38a7777a69d6b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
